---
heat_template_version: 2016-04-08

description: infrastructure cv.4

parameters:
  Cvicenie:
    description: Cislo cvicenia
    type: string
    default: cv4
    
  AvailabilityZone:
    description: Availability zone
    type: string
    default: any
    
  Flavor:
    description: Flavor
    type: string
    default: Linux
    
  Image:
    description: Image
    type: string
    default: Ubuntu server 14.04 amd64 KIS
    
  Environment:
    description: Environment
    type: string
    default: test
    
  SubnetCidr:
    description: SubnetCidr
    type: string
    default: 10.255.255.0/24
    
  AppFloatingIpID:
    description: AppFloatingIpID
    type: string
    default: a9c29d6a-91d2-4019-af37-c6e475ad36ba
  
resources:
 Net:
   type: OS::Neutron::Net
   properties:
     admin_state_up: True
     name: { list_join: [ '-', [ { get_param: 'Environment' }, 'network' ] ] }
     shared: False
     
 Subnet:
   type: OS::Neutron::Subnet
   properties:
     name: { list_join: [ '-', [ { get_param: 'Environment' }, 'subnet' ] ] }
     cidr: { get_param: 'SubnetCidr' }
     dns_nameservers:
       - 8.8.8.8
       - 8.8.4.4
     enable_dhcp: True
     network: { get_resource: Net }
     
 Router:
   type: OS::Neutron::Router
   properties:
     admin_state_up: True
     name: { list_join: [ '-', [ { get_param: 'Environment' }, 'router' ] ] }
     external_gateway_info: {
       enable_snat: True,
       network: ext-net
     }
   
 RouterInterface:
   type: OS::Neutron::RouterInterface
   properties:
     router: { get_resource: Router }
     subnet: { get_resource: Subnet }
 
 AppPrivateSecurityGroup:
   type: OS::Neutron::SecurityGroup
   properties:
     name: { list_join: ['-', [ { get_param: 'Cvicenie'}, 'app_security_group' ] ] }
     rules: [
       { direction: ingress, ethertype: IPv4, protocol: tcp, port_range_min: 1, port_range_max: 65535, remote_ip_prefix: 158.193.0.0/16 },
       { direction: ingress, ethertype: IPv4, protocol: udp, port_range_min: 1, port_range_max: 65535, remote_ip_prefix: 158.193.0.0/16 },
       { direction: ingress, ethertype: IPv4, protocol: icmp, remote_ip_prefix: 158.193.0.0/16 }
     ]
 
 AppPort:
   type: OS::Neutron::Port
   properties:
     name: { list_join: ['-', [ { get_param: 'Cvicenie'}, 'app_port' ] ] }
     fixed_ips:
       - subnet: { get_resource: Subnet }
     security_groups:
       - { get_resource: AppPrivateSecurityGroup }
     network: { get_resource: Net }
 
 App:
    type: OS::Nova::Server
    properties:
      name: { list_join: ['-', [ { get_param: 'Cvicenie'}, 'app' ] ] }
      availability_zone: { get_param: 'AvailabilityZone' }
      flavor: { get_param: 'Flavor' }
      image: { get_param: 'Image' }
      networks:
       - port: { get_resource: AppPort }
      user_data: 
        str_replace:
          template: |
            #!/bin/bash
            hostname $Environment-app
            echo "Hello World!!!"
            apt-get update -y
          params:
            $Environment: { get_param: Environment }
      user_data_format: RAW
 
 AppFloatingIpAssociation:
   type: OS::Neutron::FloatingIPAssociation
   properties:
     floatingip_id: { get_param: AppFloatingIpID }
     port_id: { get_resource: AppPort }
